repository:
  name: strava-enhancement-suite
  description: Handy tools and improvements to Strava.com
  # homepage: https://example.github.io/

  has_wiki: false

  default_branch: master

  allow_merge_commit: false
  allow_squash_merge: false
  allow_rebase_merge: true

labels:
  - name: "area: infra"
    color: FDB000
